#!/usr/bin/env bash
# Connect the shell half of this repo to the Rust half.
#
# Usage:
#   ./sync-prebuilt.sh              copy dist/* into the crate's prebuilt/ cache
#   ./sync-prebuilt.sh --headers    refresh the committed headers and the generated bindings
#   ./sync-prebuilt.sh --check      verify the committed headers and bindings
#   ./sync-prebuilt.sh --fetch      download the latest release's archives into prebuilt/
#
# Neither `prebuilt/` nor `dist/` is committed — see .gitignore. Two things *are*:
#
#   include/{freerdp3,winpr3}/   FreeRDP's and WinPR's public headers. Text, and reviewable —
#                                the opposite of a committed `.a`.
#   src/bindings.rs              generated *from* those headers by gen-bindings.sh.
#
# **The headers come from a built artifact, not from the source tarball**, and that is a real
# divergence from libvpx-prebuilt, which copies straight out of its checkout.
# `freerdp/settings_keys.h` — where every `FreeRDP_Xxx` constant lives, and therefore the whole
# configuration API — is generated at cmake *configure* time and does not exist in the tarball at
# all. Neither do freerdp/config.h, freerdp/version.h, freerdp/build-config.h or winpr/config.h.
# So the chain runs through a build:
#
#   freerdp.env pins a tarball checksum
#     -> source.sh refuses anything else
#       -> build.sh compiles it and *installs* a header tree
#         -> those headers are what is committed here
#           -> and bindings.rs is what bindgen makes of them
#
# That raises a question libvpx-prebuilt never had to answer. Those generated headers are
# **host-dependent** — `WINPR_HAVE_SYS_EVENTFD_H` on Linux, `WINPR_HAVE_SYS_FILIO_H` on Darwin —
# so the installed set is *not* byte-identical across targets, and a plain `diff -r` between
# targets cannot be the check. Two answers, both measurements rather than arguments:
#
#   - one target is canonical (below), and `--check` diffs every *other* built target against it
#     with a small committed allowlist of files permitted to differ (header-drift.allow);
#   - CI runs `gen-bindings.sh --check` on all three targets against each target's own headers
#     and requires all three to produce an identical bindings.rs. That converts "one bindings.rs
#     is portable" from an assumption into a per-release measurement.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$here"
# shellcheck source=freerdp.env
. ./freerdp.env
# shellcheck source=source.sh
. ./source.sh

crate=crates/freerdp-prebuilt-sys
prebuilt="$crate/prebuilt"

# Every target build.sh knows how to make.
targets=(macos-arm64 linux-x86_64 linux-aarch64)

# The one whose installed headers are committed.
#
# linux-x86_64 rather than whatever the developer's laptop is, and the reason is that the
# committed tree should be a property of the project rather than of a machine. It is the target
# CI builds on every push, so it is the one that can be regenerated by anybody; a Mac developer
# refreshing headers from macos-arm64 would commit `WINPR_HAVE_SYS_FILIO_H` and hand every Linux
# consumer a header set that never built on their platform.
#
# SYNC_HEADERS_FROM overrides it for the bootstrap case — the first release, before any CI run
# exists — and says so loudly, because the result is a commit nobody else's machine reproduces.
canonical="${SYNC_HEADERS_FROM:-linux-x86_64}"

# Files whose contents legitimately differ between targets. Committed, small, and read by
# --check; anything not on it must be byte-identical everywhere.
drift_allow=header-drift.allow

case "${1:-}" in
  --headers)
    src="dist/$canonical"
    [ -d "$src/include" ] || {
      echo "no built headers at $src/include" >&2
      echo "  Run ./build.sh $canonical first. The headers are generated by cmake, so there is" >&2
      echo "  no source tree to take them from — see the note at the top of this file." >&2
      exit 1
    }
    if [ "$canonical" != linux-x86_64 ]; then
      echo "!! committing headers from $canonical, not linux-x86_64." >&2
      echo "!! The generated config headers are host-dependent, so this is a commit that" >&2
      echo "!! another machine will not reproduce. Only correct while bootstrapping." >&2
    fi

    rm -rf "$crate/include"
    mkdir -p "$crate/include"
    cp -R "$src/include/freerdp3" "$crate/include/freerdp3"
    cp -R "$src/include/winpr3" "$crate/include/winpr3"
    # FreeRDP is Apache-2.0 and OpenSSL 3 is Apache-2.0; both archives ship their own copy, and
    # the repository root carries them too, where anyone looks first.
    cp "$src/LICENSE.FreeRDP" LICENSE.FreeRDP
    cp "$src/LICENSE.OpenSSL" LICENSE.OpenSSL
    echo ">> $crate/include is FreeRDP $FREERDP_VERSION's installed headers from $canonical"
    echo "   $(find "$crate/include" -name '*.h' | wc -l | tr -d ' ') headers"
    (cd "$crate" && ./gen-bindings.sh)
    ;;

  --check)
    [ -d "$crate/include/freerdp3" ] || {
      echo "no committed headers at $crate/include — run --headers" >&2
      exit 1
    }

    # Against every target sitting in dist/. The canonical one must match exactly; the others may
    # differ only in the files the allowlist names.
    checked=0
    for dir in dist/*/; do
      target="$(basename "$dir")"
      [ -d "$dir/include" ] || continue
      checked=$((checked + 1))

      # `diff -rq` names changed, missing *and* extra files — the last one matters, because
      # bindings.rs is generated from whatever is sitting in that directory.
      differences="$(diff -rq "$dir/include" "$crate/include" 2>&1 || true)"
      if [ -z "$differences" ]; then
        echo "   $target: byte-identical to the committed headers"
        continue
      fi

      if [ "$target" = "$canonical" ]; then
        echo "the committed headers are not what $canonical installs — run --headers" >&2
        head -30 <<<"$differences" >&2
        exit 1
      fi

      # Reduced to bare paths relative to the include root, then checked against the allowlist.
      unexpected=''
      while IFS= read -r line; do
        [ -n "$line" ] || continue
        path="$(sed -E "s#^Files $dir/include/(.*) and .*#\1#; s#^Only in [^:]*: #?? #" <<<"$line")"
        grep -qxF "$path" "$drift_allow" 2>/dev/null || unexpected+="$line"$'\n'
      done <<<"$differences"

      if [ -n "$unexpected" ]; then
        echo "$target's headers differ from $canonical's outside $drift_allow:" >&2
        head -30 <<<"$unexpected" >&2
        echo "  Either the difference is legitimate — a generated config header — and belongs" >&2
        echo "  on the allowlist, or something in build.sh is not configuring both the same." >&2
        exit 1
      fi
      echo "   $target: differs only in the $(wc -l < "$drift_allow" | tr -d ' ') allowlisted generated headers"
    done

    if [ "$checked" -eq 0 ]; then
      echo "   note: nothing in dist/, so the installed-header check did not run"
    fi

    # And the licences, from the pinned sources rather than from a build — these are the one
    # thing that does live in the tarballs.
    ensure_freerdp
    ensure_openssl
    diff -q "build/freerdp-${FREERDP_VERSION}/LICENSE" LICENSE.FreeRDP >/dev/null || {
      echo "LICENSE.FreeRDP is not the pinned tarball's — run --headers" >&2
      exit 1
    }
    diff -q "build/openssl-${OPENSSL_VERSION}/LICENSE.txt" LICENSE.OpenSSL >/dev/null || {
      echo "LICENSE.OpenSSL is not the pinned tarball's — run --headers" >&2
      exit 1
    }
    echo "   LICENSE.FreeRDP and LICENSE.OpenSSL match the pinned sources"

    (cd "$crate" && ./gen-bindings.sh --check)
    ;;

  --fetch)
    # For working offline afterwards, or for testing a target this machine cannot build. Takes
    # whatever the latest release holds, which is the same thing build.rs would fetch — including
    # the SHA256SUMS check, because a download verified in one half of this repository and not
    # the other is a difference someone would eventually trip over.
    base="https://github.com/$PREBUILT_REPO/releases/latest/download"
    tmp="$(mktemp -d)"
    trap 'rm -rf "$tmp"' EXIT

    echo ">> SHA256SUMS"
    curl -sSL --fail --max-time 300 -o "$tmp/SHA256SUMS" "$base/SHA256SUMS"

    for target in "${targets[@]}"; do
      asset="freerdp-${FREERDP_VERSION}-${target}.tar.gz"
      echo ">> $asset"
      curl -sSL --fail --max-time 600 -o "$tmp/$asset" "$base/$asset"

      # `./` tolerated on the name for the same reason build.rs tolerates it: how the release job
      # spelled its glob should not be able to break this.
      expected="$(awk -v a="$asset" '$2 == a || $2 == "./" a { print $1 }' "$tmp/SHA256SUMS")"
      [ -n "$expected" ] || { echo "SHA256SUMS does not list $asset" >&2; exit 1; }
      actual="$(sha256_of "$tmp/$asset")"
      [ "$actual" = "$expected" ] || {
        echo "checksum mismatch for $asset" >&2
        echo "  SHA256SUMS says $expected" >&2
        echo "  the download is $actual" >&2
        exit 1
      }

      rm -rf "${prebuilt:?}/${target:?}"
      mkdir -p "$prebuilt/$target"
      tar xzf "$tmp/$asset" -C "$prebuilt/$target"
    done
    ;;

  "")
    # The local loop: whatever ./build.sh has produced becomes what cargo links, with no release
    # and no network in the picture at all.
    [ -d dist ] || { echo "nothing in dist/ — run ./build.sh <target> first" >&2; exit 1; }
    found=0
    for dir in dist/*/; do
      target="$(basename "$dir")"
      [ -f "$dir/MANIFEST" ] || continue
      rm -rf "${prebuilt:?}/${target:?}"
      mkdir -p "$prebuilt"
      cp -R "$dir" "$prebuilt/$target"
      echo ">> $target ($(sed -n 's/^cpu_floor //p' "$dir/MANIFEST"))"
      found=$((found + 1))
    done
    [ "$found" -gt 0 ] || { echo "no built targets in dist/" >&2; exit 1; }
    echo ">> $found target(s) in $prebuilt — cargo will use these before any release"
    ;;

  *)
    sed -n '2,/^set -euo pipefail$/p' "$0" | sed '$d; s/^# \{0,1\}//'
    exit 1
    ;;
esac
