#!/usr/bin/env bash
# Connect the shell half of this repo to the Rust half.
#
# Usage:
#   ./sync-prebuilt.sh              copy dist/* into the crate's prebuilt/ cache
#   ./sync-prebuilt.sh --headers    refresh the committed headers and the generated bindings
#   ./sync-prebuilt.sh --check      verify the committed headers and bindings
#   ./sync-prebuilt.sh --fetch      download the latest release's archives into prebuilt/
#
# Neither `prebuilt/` nor `dist/` is committed — see .gitignore. Two things *are*:
#
#   include/{freerdp3,winpr3}/   FreeRDP's and WinPR's public headers. Text, and reviewable —
#                                the opposite of a committed `.a`.
#   src/bindings.rs              generated *from* those headers by gen-bindings.sh.
#
# **The headers come from a built artifact, not from the source tarball**, and that is a real
# divergence from libvpx-prebuilt, which copies straight out of its checkout.
# `freerdp/settings_keys.h` — where every `FreeRDP_Xxx` constant lives, and therefore the whole
# configuration API — is generated at cmake *configure* time and does not exist in the tarball at
# all. Neither do freerdp/config.h, freerdp/version.h, freerdp/build-config.h or winpr/config.h.
# So the chain runs through a build:
#
#   freerdp.env pins a tarball checksum
#     -> source.sh refuses anything else
#       -> build.sh compiles it and *installs* a header tree
#         -> the part of it wrapper.h reaches is what is committed here
#           -> and bindings.rs is what bindgen makes of them
#
# "the part wrapper.h reaches" is 100 headers of 261, and the rest is not a smaller claim so much
# as a more honest one. What this file is protecting is the provenance of `bindings.rs`: that the
# headers it came from are the ones this build installed, rather than a stale set from an older
# FreeRDP — which the tarball checksum would happily keep verifying, since it says nothing about
# what is committed. A header bindgen never opens is 1.2 MB in every consumer's checkout and
# evidence of nothing.
#
# That raises a question libvpx-prebuilt never had to answer. Those generated headers are
# **host-dependent** — `WINPR_HAVE_SYS_EVENTFD_H` on Linux, `WINPR_HAVE_SYS_FILIO_H` on Darwin —
# so the installed set is *not* byte-identical across targets, and a plain `diff -r` between
# targets cannot be the check. Two answers, both measurements rather than arguments:
#
#   - one target is canonical (below) and supplies the committed set; `--check` diffs every built
#     target against it with a small committed allowlist of files permitted to differ
#     (header-drift.allow). That allowlist applies to the canonical target too, because the files
#     on it are properties of the *machine* — `FREERDP_INSTALL_PREFIX` is the absolute build path,
#     `FREERDP_COMPILER_VERSION` is whatever ran — so even the same target on another runner
#     differs in them;
#   - CI runs `gen-bindings.sh --check` on all three targets against each target's own headers
#     and requires all three to produce an identical bindings.rs. That converts "one bindings.rs
#     is portable" from an assumption into a per-release measurement.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$here"
# shellcheck source=freerdp.env
. ./freerdp.env
# shellcheck source=source.sh
. ./source.sh

crate=crates/freerdp-prebuilt-sys
prebuilt="$crate/prebuilt"

# Every target build.sh knows how to make.
targets=(macos-arm64 linux-x86_64 linux-aarch64)

# The one whose installed headers are committed.
#
# linux-x86_64 rather than whatever the developer's laptop is, and the reason is that the
# committed tree should be a property of the project rather than of a machine. It is the target
# CI builds on every push, so it is the one that can be regenerated by anybody; a Mac developer
# refreshing headers from macos-arm64 would commit `WINPR_HAVE_SYS_FILIO_H` and hand every Linux
# consumer a header set that never built on their platform.
#
# SYNC_HEADERS_FROM overrides it for the bootstrap case — the first release, before any CI run
# exists — and says so loudly, because the result is a commit nobody else's machine reproduces.
canonical="${SYNC_HEADERS_FROM:-linux-x86_64}"

# Files whose contents legitimately differ between targets. Committed, small, and read by
# --check; anything not on it must be byte-identical everywhere.
drift_allow="header-drift.allow"

# The headers `wrapper.h` actually reaches, asked of the compiler rather than curated.
#
# FreeRDP installs 261 public headers and this crate's `wrapper.h` reaches 100 of them; the other
# 161 are 1.2 MB that nothing here reads — the channels the archives carry but the wrapper does not
# bind (`rdpsnd.h`, `rail.h`, `scard.h`, `urbdrc.h`), plus RAIL and the server-side API. Every
# consumer paid that in their checkout for a tree only `gen-bindings.sh` opens: `build.rs` never
# looks at `include/` at all, because the bindings are committed.
#
# **Derived, never listed.** The set is a property of `wrapper.h`, and `wrapper.h` grows the moment
# a channel gets bound — binding `rdpsnd` for audio pulls a dozen of these back. A hand-maintained
# list would be wrong the first time that happened and would fail confusingly; `cc -MM` is right by
# construction and re-derives itself.
#
# Emitted relative to the include root, sorted, one per line. `-MM` rather than `-M` so system
# headers stay out, which is the same distinction `--allowlist-file` draws in gen-bindings.sh.
reachable_headers() {
  local root="$1"
  cc -MM -I "$root/freerdp3" -I "$root/winpr3" "$crate/wrapper.h" \
    | tr ' ' '\n' \
    | sed -n "s#^$root/##p" \
    | sort -u
}

case "${1:-}" in
  --headers)
    src="dist/$canonical"
    [ -d "$src/include" ] || {
      echo "no built headers at $src/include" >&2
      echo "  Run ./build.sh $canonical first. The headers are generated by cmake, so there is" >&2
      echo "  no source tree to take them from — see the note at the top of this file." >&2
      exit 1
    }
    if [ "$canonical" != linux-x86_64 ]; then
      echo "!! committing headers from $canonical, not linux-x86_64." >&2
      echo "!! The generated config headers are host-dependent, so this is a commit that" >&2
      echo "!! another machine will not reproduce. Only correct while bootstrapping." >&2
    fi

    # Only what `wrapper.h` reaches, and asked of the compiler against the *installed* tree —
    # which is the authority, since that is what was built. See `reachable_headers`.
    # `while read` rather than the obvious builtin: macOS ships bash 3.2.
    wanted=()
    while IFS= read -r header; do wanted+=("$header"); done \
      < <(reachable_headers "$src/include")
    [ "${#wanted[@]}" -gt 50 ] || {
      echo "only ${#wanted[@]} headers reachable from wrapper.h, which cannot be right" >&2
      echo "  A parse failure in wrapper.h reports as an empty dependency list, so this is" >&2
      echo "  checked rather than trusted. Run the cc line by hand to see the error." >&2
      exit 1
    }

    rm -rf "$crate/include"
    for header in "${wanted[@]}"; do
      mkdir -p "$crate/include/$(dirname "$header")"
      cp "$src/include/$header" "$crate/include/$header"
    done
    # FreeRDP is Apache-2.0 and OpenSSL 3 is Apache-2.0; both archives ship their own copy, and
    # the repository root carries them too, where anyone looks first.
    cp "$src/LICENSE.FreeRDP" LICENSE.FreeRDP
    cp "$src/LICENSE.OpenSSL" LICENSE.OpenSSL
    echo ">> $crate/include is FreeRDP $FREERDP_VERSION's installed headers from $canonical"
    echo "   ${#wanted[@]} headers, of $(find "$src/include" -name '*.h' | wc -l | tr -d ' ') installed — what wrapper.h reaches"
    (cd "$crate" && ./gen-bindings.sh)
    ;;

  --check)
    [ -d "$crate/include/freerdp3" ] || {
      echo "no committed headers at $crate/include — run --headers" >&2
      exit 1
    }

    # Against every target sitting in dist/, and every one of them may differ only in the files
    # the allowlist names — **including the canonical target**.
    #
    # That last part was a correction. The canonical target used to have to match byte for byte,
    # on the reasoning that the committed headers came from it; CI then failed because the headers
    # committed from a `debian:trixie` container are not the ones an `ubuntu-24.04` runner
    # produces, and never can be. `build-config.h` bakes in `FREERDP_INSTALL_PREFIX` — the
    # *absolute path of the build directory* — and `buildflags.h` records the compiler version and
    # the flags cmake chose for that machine. So those files are properties of whoever ran the
    # build, not of this project, on any comparison rather than only across targets.
    #
    # **The comparison is over what `wrapper.h` reaches, not over the whole installed tree**, and
    # that is a narrowing of the claim rather than a weakening of it. What this check is for is the
    # provenance of `bindings.rs`: that the headers it was generated from are the ones this build
    # installed, rather than a stale set from an older FreeRDP that the source pin would happily
    # still verify. A header bindgen never opens proves nothing about that either way.
    #
    # Two things keep the narrowing honest. The reachable set is computed from *each target's own*
    # installed tree, so a header that has become reachable and was never committed is a missing
    # file here rather than a surprise at regeneration time. And a committed header that is no
    # longer reachable is an error too, so the tree cannot silently accumulate what `wrapper.h`
    # stopped including.
    checked=0
    for dir in dist/*/; do
      target="$(basename "$dir")"
      [ -d "$dir/include" ] || continue
      checked=$((checked + 1))

      wanted=()
      while IFS= read -r header; do wanted+=("$header"); done \
        < <(reachable_headers "$dir/include")
      [ "${#wanted[@]}" -gt 50 ] || {
        echo "only ${#wanted[@]} headers reachable from wrapper.h against $target" >&2
        echo "  A parse failure reports as an empty dependency list, so this is checked." >&2
        exit 1
      }

      # Every reachable header must be committed, and identical unless it is on the allowlist.
      missing='' differing=''
      for header in "${wanted[@]}"; do
        if [ ! -f "$crate/include/$header" ]; then
          missing+="  $header"$'\n'
        elif ! cmp -s "$dir/include/$header" "$crate/include/$header" \
          && ! grep -qxF "$header" "$drift_allow" 2>/dev/null; then
          differing+="  $header"$'\n'
        fi
      done

      if [ -n "$missing" ]; then
        echo "$target: wrapper.h reaches headers that are not committed — run --headers:" >&2
        printf '%s' "$missing" >&2
        exit 1
      fi
      if [ -n "$differing" ]; then
        echo "$target's headers differ from the committed ones outside $drift_allow:" >&2
        printf '%s' "$differing" >&2
        echo "  Either the difference is legitimate — a generated config header — and belongs" >&2
        echo "  on the allowlist, or something in build.sh is not configuring every target the" >&2
        echo "  same, or the committed headers are stale and need --headers." >&2
        exit 1
      fi

      # And nothing committed that nothing reads. Only against the canonical target, because a
      # header reachable on Linux and not on Darwin is a real thing (`#ifdef __linux__` in
      # wrapper.h's transitive includes) and would make this fire on the wrong platform.
      if [ "$target" = "$canonical" ]; then
        extra=()
        while IFS= read -r header; do extra+=("$header"); done < <(comm -13 \
          <(printf '%s\n' "${wanted[@]}") \
          <(cd "$crate/include" && find . -name '*.h' | sed 's#^\./##' | sort))
        if [ "${#extra[@]}" -gt 0 ]; then
          echo "committed headers that wrapper.h no longer reaches — run --headers:" >&2
          printf '  %s\n' "${extra[@]}" >&2
          exit 1
        fi
      fi

      echo "   $target: ${#wanted[@]} headers reachable from wrapper.h, all committed and current"
    done

    if [ "$checked" -eq 0 ]; then
      echo "   note: nothing in dist/, so the installed-header check did not run"
    fi

    # And the licences, from the pinned sources rather than from a build — these are the one
    # thing that does live in the tarballs.
    ensure_freerdp
    ensure_openssl
    diff -q "build/freerdp-${FREERDP_VERSION}/LICENSE" LICENSE.FreeRDP >/dev/null || {
      echo "LICENSE.FreeRDP is not the pinned tarball's — run --headers" >&2
      exit 1
    }
    diff -q "build/openssl-${OPENSSL_VERSION}/LICENSE.txt" LICENSE.OpenSSL >/dev/null || {
      echo "LICENSE.OpenSSL is not the pinned tarball's — run --headers" >&2
      exit 1
    }
    echo "   LICENSE.FreeRDP and LICENSE.OpenSSL match the pinned sources"

    (cd "$crate" && ./gen-bindings.sh --check)
    ;;

  --fetch)
    # For working offline afterwards, or for testing a target this machine cannot build. Takes
    # whatever the latest release holds, which is the same thing build.rs would fetch — including
    # the SHA256SUMS check, because a download verified in one half of this repository and not
    # the other is a difference someone would eventually trip over.
    base="https://github.com/$PREBUILT_REPO/releases/latest/download"
    tmp="$(mktemp -d)"
    trap 'rm -rf "$tmp"' EXIT

    echo ">> SHA256SUMS"
    curl -sSL --fail --max-time 300 -o "$tmp/SHA256SUMS" "$base/SHA256SUMS"

    for target in "${targets[@]}"; do
      asset="freerdp-${FREERDP_VERSION}-${target}.tar.gz"
      echo ">> $asset"
      curl -sSL --fail --max-time 600 -o "$tmp/$asset" "$base/$asset"

      # `./` tolerated on the name for the same reason build.rs tolerates it: how the release job
      # spelled its glob should not be able to break this.
      expected="$(awk -v a="$asset" '$2 == a || $2 == "./" a { print $1 }' "$tmp/SHA256SUMS")"
      [ -n "$expected" ] || { echo "SHA256SUMS does not list $asset" >&2; exit 1; }
      actual="$(sha256_of "$tmp/$asset")"
      [ "$actual" = "$expected" ] || {
        echo "checksum mismatch for $asset" >&2
        echo "  SHA256SUMS says $expected" >&2
        echo "  the download is $actual" >&2
        exit 1
      }

      rm -rf "${prebuilt:?}/${target:?}"
      mkdir -p "$prebuilt/$target"
      tar xzf "$tmp/$asset" -C "$prebuilt/$target"
    done
    ;;

  "")
    # The local loop: whatever ./build.sh has produced becomes what cargo links, with no release
    # and no network in the picture at all.
    [ -d dist ] || { echo "nothing in dist/ — run ./build.sh <target> first" >&2; exit 1; }
    found=0
    for dir in dist/*/; do
      target="$(basename "$dir")"
      [ -f "$dir/MANIFEST" ] || continue
      rm -rf "${prebuilt:?}/${target:?}"
      mkdir -p "$prebuilt"
      cp -R "$dir" "$prebuilt/$target"
      echo ">> $target ($(sed -n 's/^cpu_floor //p' "$dir/MANIFEST"))"
      found=$((found + 1))
    done
    [ "$found" -gt 0 ] || { echo "no built targets in dist/" >&2; exit 1; }
    echo ">> $found target(s) in $prebuilt — cargo will use these before any release"
    ;;

  *)
    sed -n '2,/^set -euo pipefail$/p' "$0" | sed '$d; s/^# \{0,1\}//'
    exit 1
    ;;
esac
